# Generated by Django 4.2.10 on 2024-02-13 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdetails',
            name='fk_created_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_fk_created_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenantdetails',
            name='fk_updated_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_fk_updated_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
