# Generated by Django 4.2.10 on 2024-02-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_system', '0002_alter_tenantdetails_fk_created_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenantdetails',
            old_name='fk_created_id',
            new_name='fk_created',
        ),
        migrations.RenameField(
            model_name='tenantdetails',
            old_name='fk_updated_id',
            new_name='fk_updated',
        ),
    ]
