# Generated by Django 4.2.10 on 2024-02-13 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=150, null=True)),
                ('vchr_address', models.CharField(blank=True, max_length=350, null=True)),
                ('vchr_location', models.CharField(blank=True, max_length=350, null=True)),
                ('txt_features', models.TextField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('fk_created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_fk_created', to=settings.AUTH_USER_MODEL)),
                ('fk_updated_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_fk_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_master',
            },
        ),
        migrations.CreateModel(
            name='UnitTypes',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=150, null=True)),
                ('vchr_code', models.CharField(blank=True, max_length=150, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unit_types',
            },
        ),
        migrations.CreateModel(
            name='PropertyUnitDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dbl_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dat_agreement_end', models.DateTimeField(blank=True, null=True)),
                ('dat_rent_payout', models.DateTimeField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('fk_created_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_units_fk_created', to=settings.AUTH_USER_MODEL)),
                ('fk_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_master_id', to='property.propertymaster')),
                ('fk_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_selected_id', to='tenant_system.tenantdetails')),
                ('fk_unit_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='unit_types_selected_id', to='property.unittypes')),
                ('fk_updated_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='property_units_fk_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_unit_details',
            },
        ),
    ]
