# Generated by Django 4.2.10 on 2024-02-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertymaster',
            old_name='fk_created_id',
            new_name='fk_created',
        ),
        migrations.RenameField(
            model_name='propertymaster',
            old_name='fk_updated_id',
            new_name='fk_updated',
        ),
        migrations.RenameField(
            model_name='propertyunitdetails',
            old_name='fk_created_id',
            new_name='fk_created',
        ),
        migrations.RenameField(
            model_name='propertyunitdetails',
            old_name='fk_updated_id',
            new_name='fk_updated',
        ),
    ]
