# Generated by Django 4.2.10 on 2024-02-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_fk_created_id_propertymaster_fk_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyunitdetails',
            name='dat_agreement_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyunitdetails',
            name='dat_rent_payout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
